export const DEFAULT_PLAYERS = [
  {
    id: 1,
    name: "Mason Roberts",
    position: "Goalkeeper",
    age: 28,
    nationality: "England",
    rating: 88,
    starter: true,
  },
  {
    id: 2,
    name: "Ethan Clarke",
    position: "Right Back",
    age: 25,
    nationality: "Scotland",
    rating: 84,
    starter: true,
  },
  {
    id: 3,
    name: "Lucas Bennett",
    position: "Center Back",
    age: 30,
    nationality: "Wales",
    rating: 86,
    starter: true,
  },
  {
    id: 4,
    name: "Noah Parker",
    position: "Center Back",
    age: 27,
    nationality: "Ireland",
    rating: 85,
    starter: true,
  },
  {
    id: 5,
    name: "Daniel Hughes",
    position: "Left Back",
    age: 26,
    nationality: "England",
    rating: 83,
    starter: true,
  },
  {
    id: 6,
    name: "Oliver Grant",
    position: "Midfielder",
    age: 24,
    nationality: "France",
    rating: 87,
    starter: true,
  },
  {
    id: 7,
    name: "Leo Martin",
    position: "Midfielder",
    age: 29,
    nationality: "Portugal",
    rating: 89,
    starter: true,
  },
  {
    id: 8,
    name: "Sami Rahman",
    position: "Winger",
    age: 23,
    nationality: "Morocco",
    rating: 82,
    starter: true,
  },
  {
    id: 9,
    name: "Kian Lewis",
    position: "Striker",
    age: 26,
    nationality: "Brazil",
    rating: 90,
    starter: true,
  },
  {
    id: 10,
    name: "Aiden Cole",
    position: "Winger",
    age: 22,
    nationality: "Netherlands",
    rating: 81,
    starter: true,
  },
  {
    id: 11,
    name: "Rafael Silva",
    position: "Striker",
    age: 31,
    nationality: "Brazil",
    rating: 88,
    starter: true,
  },
  {
    id: 12,
    name: "Theo White",
    position: "Midfielder",
    age: 21,
    nationality: "Germany",
    rating: 76,
    starter: false,
  },
  {
    id: 13,
    name: "Harvey Turner",
    position: "Forward",
    age: 24,
    nationality: "England",
    rating: 78,
    starter: false,
  },
  {
    id: 14,
    name: "Isaac Foster",
    position: "Defender",
    age: 27,
    nationality: "USA",
    rating: 80,
    starter: false,
  },
  {
    id: 15,
    name: "Eli Brooks",
    position: "Goalkeeper",
    age: 20,
    nationality: "France",
    rating: 73,
    starter: false,
  },
];

export const FORM_POSITIONS = [
  "Goalkeeper",
  "Right Back",
  "Center Back",
  "Left Back",
  "Midfielder",
  "Winger",
  "Striker",
  "Forward",
  "Defender",
];
